version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: repertoirephoto
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  nextjs:
    image: node:18
    working_dir: /app
    command: sh -c "npm install && npx prisma generate && npx prisma migrate dev && npm run build && npm run start"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/repertoirephoto
    ports:
      - "3005:3000"
    volumes:
      - ./:/app
      - uploads_data:/app/uploads
    depends_on:
      - db

volumes:
  db_data:
  uploads_data:
